apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myhelmrelease
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./my-app-chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: myvalues
    valuesKey: values-dev.yaml